### ISSUE TITLE
Dead Bodies

### ISSUE THREAD

**Issue by ZAJohan** [recce-gaming/recce-missions#10]
Dead bodies of players (and certain AI) should not disappear. 
Hostile Commanders AI needs to remain there for identification
Players' bodies need to remain there so their gear is available to other players.
Currently, player bodies disappear when they die and another player examines or treats them.

**Comment by adampiskorski** [comment]
Are AI bodies disappearing now?

**Comment by ZAJohan** [comment]
No, but as per input from some members, the "garbage removal" (or something like that), will help with performance...problem is, I would like at least 30 bodies -which includes specifically 10 from their "Command" unit, to not disappear...if that is possible?
(Unless 80 dead bodies won't affect performance?)

**Comment by adampiskorski** [comment]
I haven't come across a garbage collector that is that fine-grained, that you can have a max body amount while excluding certain units. I'm not even sure which mods are currently doing garbage collection if any.
A custom garbage collector shouldn't be too hard.

As for the human players, that is a completely different issue. I'm not sure if making the bodies disappear is inherent to how the game engine works when players disconnect and there is no AI on the server.
Will have to better understand current behaviour.

**Comment by ZAJohan** [comment]
For what it's worth, the bodies currently disappears whether they stay connected or not. (E.g. Your body also disappeared to your team mates during Zeelie, even though the spectator could still see it.)

**Comment by adampiskorski** [comment]
To exclude units from corpse collector, use 
```sqf
removeFromRemainsCollector [unit1, unit2, vehicle1];
```
or in their init put
```sqf
removeFromRemainsCollector [this];
```
I can't differentiate between different AI men with this system, but I am assuming that there will only be a small number of dead special AI men that need to be kept, so they can all be excluded from the corpse collector.
