### ISSUE TITLE
ZARTY Rounds Limits

### ISSUE THREAD

**Issue by ZAJohan** [recce-gaming/recce-missions#2]
The own arty currently has unlimited rounds. This enables the players to clear the entire map of hostiles by just using Artillery. We need to limit it to 230 rounds in total.

**Comment by adampiskorski** [comment]
I'll add a counter to their ammo replenisher script in their init.
Can you please tell me how many HE rounds they get by default (without replenishment)? That needs to be taken into account by the counter in order to avoid going over 230

**Comment by ZAJohan** [comment]
Thank you very much. 
It holds 30 HE rounds by default.

**Comment by adampiskorski** [comment]
Done with merge (forgot to reference)
