### ISSUE TITLE
Weather conditions setting

### ISSUE THREAD

**Issue by ZAJohan** [recce-gaming/recce-missions#7]
Winds must be strong (15 to 30 knots random), but at a different random direction for each mission. 
We can have it so we either tell the teams what the winds are right before the mission starts, or allow them to measure it.
Currently, Eden wind settings does not seem to work on Dedicated Server even with Ace weather disabled.
Suggestions very welcome.

**Comment by adampiskorski** [comment]
I think with these it should be doable:
https://community.bistudio.com/wiki/setWind
https://community.bistudio.com/wiki/setGusts
https://community.bistudio.com/wiki/setWindDir

**Comment by adampiskorski** [comment]
For measuring, Shift + K to get a general indicator, or give them a Kestral to get exact values.
