### ISSUE TITLE
Sleep Animation

### ISSUE THREAD

**Issue by ZAJohan** [recce-gaming/recce-missions#8]
About 60 AI to be in “sleep” animation, wake up with Blufor detected by Opfor trigger. 
During previous Prelude mission Likkewaan, a injured script was used. 
Currently experimenting with Phoenix's script that ran for the Engineers. 
Any input very welcome.

**Comment by adampiskorski** [comment]
I was wanting to make a script like that for Zulu-Alpha as well.
Do you want to perhaps call the script for each unit that you want to sleep with the trigger in question as a parameter?

**Comment by ZAJohan** [comment]
Not sure what that entails. 
Effectively, I want specific units (identified by their Variable names {let's say: Swapo1; Swapo2 etc.}), to start off "sleeping". 
On the Blufor Detected by Opfor trigger zone, they should come out of this animation, and get up and be "normal" again. I.e. Go into combat mode.
They can all come out of sleep at the same time, or with a couple of seconds delay between each one -whatever will be best for performance.

**Comment by adampiskorski** [comment]
What I have in mind would give you that desired behaviour.
It wouldn't require naming units, as IMHO referring to units via variable name is seldom elegant and can lead to more errors.

**Comment by adampiskorski** [comment]
# Team Sleep

## Description

Makes any units from any group choose they're own beds (only tested with sleeping bags) to sleep at until they are awoken by given triggers.
This is MP tested on a dedicated server with headless clients.
When sleeping, the AI are careless, cannot move and have their ability to see disabled (ray casting), but they can still hear, though not well. When one of the synchronized triggers is activated, they will then wake up randomly between 1 to 7 seconds after the trigger and be fully restored.

## Installation

1. Copy over `teamSleep` folder to the root of your mission directory.
2. Merge the contents of `description.ext` with your own.
3. Follow the below **Usage** section.

## Usage

Place a game logic, sleeping bags (or any other object), men to sleep in them and
triggers (any number) to wake them up and sync all of those to the game logic.
![example_1](https://user-images.githubusercontent.com/7703045/56447385-40d37980-6308-11e9-99ce-e70fd71b32c9.jpg)
Then in the game
logic call this function in it's init with:

```sqf
nul = [this] call teamSleep_fnc_init;
```

![example_2](https://user-images.githubusercontent.com/7703045/56447388-44ff9700-6308-11e9-8c53-c570f1e1541e.jpg)

Note that if there are too few beds, then the remaining men will just sleep on the
ground where they stand.
